language: php

before_install:
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.6" ]]; then composer require --dev --no-update phpunit/phpunit 5.7.5; fi

install:
   - composer self-update
   - composer update --prefer-dist --no-interaction

php:
  - 7.0
  - 5.6

before_script:
  - composer install
  - composer require symfony/symfony:^3.1

script:
  - vendor/bin/phpunit --configuration travis.phpunit.xml
