language: php

install:
   - composer self-update
   - composer update --prefer-dist --no-interaction

php:
  - 7.0
  - 5.6

before_script:
  - composer install --dev
  - composer require symfony/symfony:3.1.*
  - composer require symfony/monolog-bundle:^2.8

script:
  - vendor/bin/phpunit --configuration travis.phpunit.xml
